baseURL = "/"
languageCode = "en-us"
title = "DSSL @ CSU"
theme = "hugo-theme-noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Add your Disqus shortname here.
disqusShortname = ""    

# github pages
publishDir = "../dssl-csu.github.io"


# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = false

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Data Science and Statistical Learning Journal Club @ CSU"

    showReadMore = false

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "dssl.csu@gmail.com"

	# Programming
  github = "https://github.com/dssl-csu"


[permalinks]
    topics = "/:year/:month/:day/:slug/"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	name = "Schedule"
	identifier = "schedule"
	url = "/"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3


